# Generated by Django 4.2.1 on 2023-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
                ('stud_gender', models.CharField(max_length=10)),
                ('stud_email', models.CharField(max_length=100)),
                ('stud_address', models.CharField(max_length=100)),
            ],
        ),
    ]
