# Generated by Django 4.2.1 on 2023-05-18 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_id', models.UUIDField(default=uuid.uuid3)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
            ],
        ),
    ]
