# Generated by Django 4.2.1 on 2023-05-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_cricketers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketers',
            name='cricket_id',
        ),
    ]
