# Generated by Django 4.2.1 on 2023-05-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
